/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: anuB_Bios Corp (https://sketchfab.com/anuB_Bios)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cartoon-rake-low-poly-e768b8fdddfe48b8b12a5d4efbc47d53
title: cartoon rake low poly
*/

import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

import glb from './out.glb'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, glb)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -2.2, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.5, 0.5, 0.5]}>
        <mesh material={materials.grb1} geometry={nodes.mesh_0.geometry} />
        <mesh material={materials.grb2} geometry={nodes.mesh_1.geometry} />
        <mesh material={materials.grb3} geometry={nodes.mesh_2.geometry} />
      </group>
    </group>
  )
}
